"""
export_weights.py  —  Export Keras model weights as ESP32 C++ header
=====================================================================
Run this AFTER train_classifier.py

Reads motion_classifier.h5 and writes ESP32_LD2450/tinyml_weights.h
containing all layer weights as static float arrays — no library needed.

Usage:
    python export_weights.py
"""

import numpy as np
from tensorflow import keras
import os

MODEL_PATH  = 'motion_classifier.h5'
OUTPUT_PATH = os.path.join('ESP32_LD2450', 'tinyml_weights.h')
CLASSES     = ['STATIC', 'CREEPING', 'WALKING', 'RUNNING', 'PACING']

print("=" * 60)
print("  LD2450 TinyML — Weight Export to C Header")
print("=" * 60)

# ── Load model ──────────────────────────────────────────────────────────────
if not os.path.exists(MODEL_PATH):
    print(f"❌ {MODEL_PATH} not found. Run train_classifier.py first.")
    exit(1)

model = keras.models.load_model(MODEL_PATH)
print(f"\n✅ Loaded: {MODEL_PATH}")

# Extract Dense layers only (skip Input, Dropout — Dropout is inactive at inference)
dense_layers = [l for l in model.layers if isinstance(l, keras.layers.Dense)]
print(f"   Dense layers found: {len(dense_layers)}")
for i, l in enumerate(dense_layers):
    W, b = l.get_weights()
    print(f"   Layer {i+1}: Dense({l.units})  W={W.shape}  b={b.shape}")

# ── Write header ────────────────────────────────────────────────────────────
os.makedirs('ESP32_LD2450', exist_ok=True)

with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:

    f.write('#pragma once\n')
    f.write('// ================================================================\n')
    f.write('// tinyml_weights.h  —  Auto-generated by export_weights.py\n')
    f.write('// DO NOT EDIT — regenerate by running export_weights.py\n')
    f.write('// ================================================================\n\n')

    # Architecture constants
    f.write('// ── Architecture ────────────────────────────────────────────────\n')
    f.write('#define ML_WINDOW_SIZE   10    // frames\n')
    f.write('#define ML_N_FEATURES     7    // features per frame\n')
    f.write('#define ML_INPUT_SIZE    70    // WINDOW_SIZE * N_FEATURES\n')
    f.write(f'#define ML_N_CLASSES      {len(CLASSES)}    // output classes\n\n')

    # Class name strings
    f.write('// ── Class Labels ────────────────────────────────────────────────\n')
    f.write('static const char* const ML_CLASSES[ML_N_CLASSES] = {\n')
    f.write('    ' + ', '.join(f'"{c}"' for c in CLASSES) + '\n')
    f.write('};\n\n')

    # Normalization constants (must match train_classifier.py)
    f.write('// ── Normalization (must match train_classifier.py) ───────────────\n')
    f.write('#define ML_NORM_X       4000.0f\n')
    f.write('#define ML_NORM_Y       8000.0f\n')
    f.write('#define ML_NORM_SPD        4.0f\n')
    f.write('#define ML_NORM_DIST    8000.0f\n')
    f.write('#define ML_NORM_THR      100.0f\n')
    f.write('#define ML_NORM_DXDY     300.0f\n\n')

    # Export each layer's weights and biases
    for idx, layer in enumerate(dense_layers):
        W, b = layer.get_weights()
        in_dim, out_dim = W.shape
        layer_num = idx + 1

        f.write(f'// ── Layer {layer_num}: Dense({out_dim})  in={in_dim} ─────────────────────────\n')

        # Weight matrix: W[in_dim][out_dim]
        # Keras stores W as (in_dim, out_dim) which is exactly W[i][j]
        f.write(f'static const float ML_W{layer_num}[{in_dim}][{out_dim}] = {{\n')
        for i in range(in_dim):
            row_vals = ', '.join(f'{W[i, j]:.7f}f' for j in range(out_dim))
            f.write(f'    {{ {row_vals} }},\n')
        f.write('};\n\n')

        # Bias vector: b[out_dim]
        f.write(f'static const float ML_B{layer_num}[{out_dim}] = {{\n    ')
        f.write(', '.join(f'{v:.7f}f' for v in b))
        f.write('\n};\n\n')

# ── Summary ──────────────────────────────────────────────────────────────────
file_size = os.path.getsize(OUTPUT_PATH)
print(f"\n✅ Written: {OUTPUT_PATH}  ({file_size / 1024:.1f} KB)")
print(f"\n   Layers exported: {len(dense_layers)}")

total_params = 0
for idx, layer in enumerate(dense_layers):
    W, b = layer.get_weights()
    params = W.size + b.size
    total_params += params
    print(f"   Layer {idx+1}: {params:>6} parameters  ({params * 4 / 1024:.1f} KB)")

print(f"   Total : {total_params:>6} parameters  ({total_params * 4 / 1024:.1f} KB in flash)")
print(f"\n▶  Next step: see INTEGRATION_GUIDE.md or flash with esphome run")
